config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  if ENVied.LIVE
    root to: 'static#home'
  else
    get '/home', to: 'static#home', as: :root

    if (url = ENV['TEMPORARY_REDIRECT_ROOT_ROUTE'].presence)
      get '/', to: redirect(url, status: 302)
    else
      get '/', to: 'static#coming_soon', as: :coming_soon
    end
  end

  devise_for :users, controller: { sessions: 'users/sessions' }

  get '/auth/:provider/callback', to: 'omniauth#callback'
  get '/auth/failure', to: redirect('/')

  devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
  end

  get 'welcome', to: 'welcome#new', as: :welcome
  get 'welcome/:token', to: 'welcome#new'

  get 'account', to: 'users#edit', as: :account
  put 'account', to: 'users#update'
  get 'users/new', to: 'users#new', as: :new_user
  post 'users', to: 'users#create', as: :users

  get 'actions', to: 'actions#index', as: :actions
  get 'action', to: 'actions#show', as: :action
  post 'action', to: 'responses#create', as: :response

  namespace :admin do
    get 'projects', to: 'projects#index', as: :projects
    get 'projects/:key/edit', to: 'projects#edit', as: :edit_project
    put 'projects/:key', to: 'projects#update', as: :project

    get 'responses', to: 'responses#index', as: :responses
    get 'responses/:token', to: 'responses#show', as: :response
    put 'responses/:token', to: 'responses#update'

    resources 'cities', except: [:edit, :update]
    resources 'domains', except: :show
    resources 'users', only: 'index'

    authenticate :user, -> (u) { u.admin } do
      mount Sidekiq::Web => '/sidekiq'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :legacy_survey_response, optional: true

  devise :database_authenticatable, :recoverable, :rememberable, :trackable,
    :validatable

  validates :email, uniqueness: true, allow_blank: true
  validates :external_uid_facebook, uniqueness: true, allow_blank: true
  validate :has_email_or_external_uid

  before_create do
    if legacy_survey_response_id.present?
      object = LegacySurveyResponse.find(legacy_survey_response_id)
      object.statistics.redeemed!
    end
  end

  before_validation do
    begin
      populate_location_columns
    rescue ::LocationResolutionError => ex
      errors.add(:location, ex.message)
    end
  end

  def inflate_from_legacy_survey_response(legacy_survey_response)
    self.name = legacy_survey_response.name
    self.email = legacy_survey_response.email
    self.location = legacy_survey_response.zip_code

    self.legacy_survey_response_id = legacy_survey_response.id
  end

  def statistics
    ResponseStatistics.where(user: self).first_or_create
  end

  def self.find_or_create_by_omniauth_hash(auth_hash)
    id_column = ['external_uid', auth_hash.provider].join('_')
    where(id_column => auth_hash.uid).first_or_create!(
      name: auth_hash.info.name,
    )
  end

  def has_email_or_external_uid
    return if is_external?
    return if email.present?
    errors.add(:email, 'must be present')
  end

  def is_external?
    external_uid_facebook.present?
  end

  def email_required?
    ! is_external?
  end

  def password_required?
    ! is_external?
  end

  def populate_location_columns
    return unless location.present?

    result = Location.location(location)

    self.latitude = result.latitude
    self.longitude = result.longitude
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < Admin::BaseController
  def index
    @users = User.all
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def create
    super
    session.delete(stored_location_key_for(:user))
  end

  def destroy
    super
    reset_session
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate!, only: [:edit, :update]
  before_action :set_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(new_user_params)

    if @user.save
      sign_in(:user, @user)
      redirect_to after_sign_in_path_for(:user)
    else
      case params[:user][:referrer]
      when 'welcome'
        render 'welcome/new'
      when 'homepage', 'sign-up'
        render 'users/new'
      else
        raise
      end
    end
  end

  def update
    old_password = edit_user_params[:old_password]
    new_password = edit_user_params[:new_password]

    edit_user_params.delete(:old_password)
    edit_user_params.delete(:new_password)

    @user.assign_attributes(edit_user_params)

    if @user.password_required? && ! @user.valid_password?(old_password)
      @user.errors.add(:old_password, 'was not correct')
      render :edit
      return
    end

    if new_password.present?
      @user.password = new_password
    else
      @user.password = old_password
    end

    if @user.save && sign_in(@user, :bypass => true)
      flash[:notice] = 'Your account has been successfully updated.'
      redirect_to actions_path
    else
      render :edit
    end
  end

  private

  def set_user
    @user = current_user
  end

  def edit_user_params
    @_edit_user_params ||= params.require(:user).permit(
      :email,
      :is_organization,
      :location,
      :name,
      :new_password,
      :old_password,
      :organization_name,
      :phone,
    )
  end

  def new_user_params
    @_new_user_params ||= params.require(:user).permit(
      :email,
      :is_organization,
      :legacy_survey_response_id,
      :location,
      :name,
      :organization_name,
      :password,
      :phone,
    )
  end
end

app/views/users/edit.html.haml
.container
  .row
    .col-xs-12
      %h1 My Account

  .row
    .col-sm-6
      = simple_form_for(@user, url: account_path, method: :put) do |form|
        = form.input :name
        = form.input :email
        = form.input :location
        = form.input :phone, label: 'Phone number <span class="italic">(to receive text alerts)</span>'.html_safe
        = form.input :is_organization, label: 'I represent an organization or company', as: :boolean
        %input.form-control.string.optional#user_organization_name{placeholder: 'Organization/Company Name', type: 'text', name: 'user[organization_name]', value: @user.organization_name}
        - if @user.password_required?
          = form.input :old_password, label: 'Current password'
          = form.input :new_password
        = form.button :submit, 'Update', class: 'btn-primary margin-top-4'

app/views/users/new.html.haml
.container
  .row
    .col-xs-12
      %h1 Sign Up

  .row
    .col-sm-6
      = simple_form_for(@user, url: users_path, method: :post) do |form|
        = form.hidden_field :referrer, value: 'sign-up'
        = form.input :name
        = form.input :email, required: true
        = form.input :password, required: true
        = form.input :location, label: 'Zip Code or Location'
        = form.input :phone, label: 'Phone number <span class="italic">(to receive text alerts)</span>'.html_safe
        = form.input :is_organization, label: 'My organization or company would like to join this coalition'
        %input.form-control.string.optional#user_organization_name{placeholder: 'Organization/Company Name', type: 'text', name: 'user[organization_name]', value: @user.organization_name}
        = form.button :submit, 'Sign Up', class: 'btn-primary margin-top-4'

      .or OR
      %a.btn.btn-facebook(href="/auth/facebook") Sign up with Facebook